# Minecraft server properties

motd=Lazr Space\: Vanilla
server-port=25565
server-ip=
enable-query=false
enable-status=true
query.port=25565

# Remote console settings.
enable-rcon=true
broadcast-rcon-to-ops=true
rcon.password=j83Q5XzbJuDuM4TniNsVikcH0
rcon.port=25575

# Players.
white-list=true
enforce-whitelist=true
max-players=20
hide-online-players=false
player-idle-timeout=0
text-filtering-config=

# World settings
gamemode=survival
force-gamemode=false
difficulty=easy
enable-command-block=true
allow-flight=false
allow-nether=true
hardcore=false
online-mode=true
view-distance=10
pvp=true
max-build-height=256

# Level generation
generator-settings=
level-name=vanilla
level-seed=
level-type=default
generate-structures=true
max-tick-time=60000
max-world-size=29999984
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=16
entity-broadcast-range-percentage=100
sync-chunk-writes=true
simulation-distance=10

# Network tunables.
prevent-proxy-connections=false
network-compression-threshold=256
rate-limit=0
use-native-transport=true

# Debugging and maintenance.
debug=false
broadcast-console-to-ops=true
enable-jmx-monitoring=false
function-permission-level=2
op-permission-level=4
snooper-enabled=true

require-resource-pack=false
resource-pack=
resource-pack-prompt=
resource-pack-sha1=

