# Bird camera enabled site

server {
    listen 80;
    types {
	application/vnd.apple.mpegurl m3u8;
	video/mp4 mp4;
	text/html html;
    }

    location / {
    	root /var/www/html;
    }

    location /hls {
    	autoindex on;
        root /tmp/live-stream-hls;

	# To avoid issues with cross-domain HTTP requests (e.g. during development)
	add_header Access-Control-Allow-Origin *;
    }

    # rtmp stat
    location /live/stat {
	rtmp_stat all;
	rtmp_stat_stylesheet stat.xsl;
    }

    location /live/stat.xsl {
	# you can move stat.xsl to a different location
        alias /var/www/html/stat.xsl;
    }
}