server.modules += ("mod_rewrite", "mod_proxy")

var.tld = "\.lazr\.internal$"

$SERVER["socket"] == ":80" {
  $HTTP["host"] =~ "^home(-assistant)?" + tld {
    proxy.server = ( "" => (( "host" => "localhost", "port" => 8123 )))
  }
  $HTTP["host"] =~ "^pihole" + tld {
    url.redirect = ( "" => "http://baked.lazr.internal/admin${url.path}${qsa}" )
  }
}
